version: '3'

services:

  media-db:
    container_name: object-media-db
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=magcentre
      - MYSQL_DATABASE=media-registry
    networks:
      - cloud-network
    volumes:
      - /home/prasanna/container-stroage/object-media:/var/lib/mysql

  service:
    container_name: object-media-service
    depends_on:
      - media-db
    build: .
    restart: unless-stopped
    ports:
      - 5006:5006
    stdin_open: true
    tty: true
    networks:
      - cloud-network

networks:
  cloud-network:
    name: cloud-network
